alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: mvc
region: fra
services:
- name: mvc
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xs
  image:
    registry_type: DOCR
    repository: registry.digitalocean.com/dnw/mvc
    tag: latest
  envs:
    - key: ASPNETCORE_ENVIRONMENT
      scope: RUN_AND_BUILD_TIME
      value: Production