  name: Build and deploy
  
  on:
    push:
      branches:
        - master
          
  env:
    REGISTRY: registry.digitalocean.com/dnw/
    IMAGE_TAG: dnw2022/mvc:latest 
        
  jobs:
    build:
      
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout files
          uses: actions/checkout@v2
          
#        - name: List files
#          run: |
#            pwd
#            ls -la
#            cat ./.deploy/deploy.yaml

        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

        - name: Login to Digital Ocean Registry
          run: doctl registry login --expiry-seconds 600    

        - name: Create deploy image
          run: docker build -t dnw2022/mvc:latest -f Dockerfile .

        - name: Tag image
          run: docker image tag dnw2022/mvc:latest registry.digitalocean.com/dnw/dnw2022:mvc-latest

        - name: Push deploy image to Digital Ocean Registry
          run: docker push registry.digitalocean.com/dnw/dnw2022:mvc-latest

        - name: Redeploy app
          run: doctl apps create --spec ./.deploy/deploy.yaml --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --upsert --wait